name: Build Toolchain

on:
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        target: [mipsel-linux-musl, mipsel-linux-uclibc]

    steps:
      - uses: actions/checkout@main

      - name: Install Build Dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y bison flex gperf help2man libtool-bin texinfo

      - name: Build and Package
        run: |
          make CT_TARGET=${{ matrix.target }}
          cd "${{ matrix.target }}"
          tar cJf "../${{ matrix.target }}.tar.xz" .
        working-directory: toolchain

      - uses: actions/upload-artifact@main
        with:
          name: ${{ matrix.target }}
          path: toolchain/${{ matrix.target }}.tar.xz

      - uses: ncipollo/release-action@main
        with:
          tag: toolchain
          artifacts: toolchain/${{ matrix.target }}.tar.xz
          allowUpdates: true
          omitBodyDuringUpdate: true